### ISSUE TITLE
Barcode request

### ISSUE THREAD

**Issue by hmdadou** [DevJMD/TescoNodeAPI#1]
Hi there is there a way to get product price or info using tesco's barcode product?
Thank you for your cooperation

**Comment by DevJMD** [comment]
Unfortunately, the only two API's currently exposed are "Store Locations" and "Grocery". I'm as hopeful as you for the dev team to enable the EAN barcode search in the near future.

I'll keep this in mind as a future enhancement when it becomes available.

Cheers!
